#!/usr/bin/env bash

set -e

# Tiling config (-t parameter)
#
# T might need to be adjusted for different window managers
# WAIT might need to be increased for plots that render too slowly
Y=100 # Y origin
W=640 # plot width
H=400 # plot height
T=38 # title bar height
WAIT=1 # plot rendering wait time

# parse command line args
while [[ $# -gt 0 ]]; do
    case $1 in
      -p|--plot) # skip the run and just xplot the plots
        skip_run=1
        shift
        ;;
      -r|--realtime) # preface run with chrt 10 to give it realtime priority
        realtime="sudo chrt 10"
        shift
        ;;
      -t|--tile) # tile plots using wmctrl (which must be installed)
        if ! command -v wmctrl &> /dev/null; then
            >&2 echo "-t argument for tiling requires wmctrl command"
            exit 1
        fi
        tile=1
        shift
        ;;
    esac
done

if [[ $skip_run != 1 ]]; then
    # clean, build and generate plots
    rm -f *.xpl
    go build
    $realtime ./scim
fi

# display plots, either with tiling or without
if [[ $tile == 1 ]]; then
    xplot thruput.xpl &> /dev/null &
    sleep $WAIT
    wmctrl -r xplot -T "IP Throughput"
    wmctrl -r "IP Throughput" -e 0,0,$Y,$W,$H
    
    xplot sojourn.xpl &> /dev/null &
    sleep $WAIT
    wmctrl -r xplot -T "Sojourn"
    wmctrl -r "Sojourn" -e 0,$W,$Y,$W,$H
    
    xplot cwnd.xpl &> /dev/null &
    sleep $WAIT
    wmctrl -r xplot -T "cwnd"
    wmctrl -r "cwnd" -e 0,0,$((Y+H+T)),$W,$H
    
    xplot mark-frequency.xpl &> /dev/null &
    sleep $WAIT
    wmctrl -r xplot -T "Mark Frequency"
    wmctrl -r "Mark Frequency" -e 0,$W,$((Y+H+T)),$W,$H
elif command -v xplot &> /dev/null; then
    xplot *.xpl &>/dev/null &
fi
